databases:
  - name: postgres
    ipAllowList: []
    region: frankfurt
    plan: free
services:
  - type: web
    plan: free
    name: Eighthon
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 rep.py & bash eigthon.py
    region: frankfurt
    envVars:
      - key: API_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: TERMUX
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: TZ
        value: Asia/Baghdad 
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString   
    autoDeploy: false
